---
- name: Install NATS CLI package from the nats-io/natscli GitHub repository's releases.
  ansible.builtin.apt:
    state: present
    deb: "https://github.com/nats-io/natscli/releases/download/\
      v{{ natscli_version }}/nats-{{ natscli_version }}-{{ natscli_arch }}.deb"
